#!/bin/bash

packages="python3 python3-pip python3-setuptools nmap sshpass"

apt -y install $packages

pip3 install wheel
pip3 install tensorflow==1.5
pip3 install keras==2.1.5 -i https://pypi.tuna.tsinghua.edu.cn/simple

python_packages="numpy glob2 flask requests pandas ipaddress regex"

pip3 install $python_packages

python3 -c 'import tensorflow as tf'
python3 -c 'import keras'
python3 -c 'from keras.datasets import mnist'
python3 -c 'from keras.models import Sequential'
python3 -c 'from keras.layers import Dense, Dropout, Flatten'
python3 -c 'from keras.layers import Conv2D, MaxPooling2D'
python3 -c 'from datetime import datetime'

python3 -c 'import numpy as np'
python3 -c 'import glob'
python3 -c 'from flask import Flask, request'
python3 -c 'import json'
python3 -c 'import requests'
python3 -c 'import ast'

#packages="python3 python3-pip python3-setuptools"

#apt -y install sshpass
#apt -y install nmap

#py_pack="python3-setuptools"

#apt-get install $py_pack

#pip3 install wheel

#python3 setup.py bdist_wheel

#pip3 install numpy
#pip3 install Cython
#python3 -m pip install scikit-learn
#pip3 install scipy


#python_packages="pandas ipaddress regex"

#pip3 install $python_packages


#echo 'export GOPATH=$HOME/go' >> ~/.bashrc
#echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' >> ~/.bashrc
#mkdir ~/go
#source ~/.bashrc && go version

#go_packages="github.com/go-sql-driver/mysql github.com/mattn/go-shellwords"

#go get $go_packages
