#!/bin/bash

packages="python3 python3-pip python3-setuptools"

apt -y install $packages

#py_pack="python3-setuptools"

#apt-get install $py_pack

pip3 install wheel

#python3 setup.py bdist_wheel

pip3 install numpy
pip3 install Cython
#python3 -m pip install scikit-learn
pip3 install scipy


python_packages="pandas ipaddress regex"

pip3 install $python_packages


#echo 'export GOPATH=$HOME/go' >> ~/.bashrc
#echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' >> ~/.bashrc
#mkdir ~/go
#source ~/.bashrc && go version

#go_packages="github.com/go-sql-driver/mysql github.com/mattn/go-shellwords"

#go get $go_packages
